# Taps
tap "homebrew/bundle"
tap "homebrew/core"

# Binaries
brew "dockutil"
brew "git"
brew "fzf"
brew "youtube-dl"
brew "ffmpeg"
brew "htop"
brew "wget"
brew "gh"
brew "wakeonlan"

# Development
brew "php"
brew "php@7.4"
brew "php@7.3"
brew "composer"
brew "node"
brew "yarn"

# Applications
cask "1password"
# cask "alfred"
cask "atom"
cask "visual-studio-code"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "postman"
cask "rectangle"
cask "slack"
cask "spotify"
cask "tableplus"
cask "the-unarchiver"
cask "transmit"
cask "alacritty"

# Quick Look
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
